### PR TITLE
Update icon for Twitter

### PR DESCRIPTION
**Pull request by ch3thanhs**
I have updated the icon for Twitter with the new X, might also have to change the name to "x.png", after they make it the main domain.

### CODE REVIEW

**Comment by OmarNazzal150** [comment]
And also update the Roblox icon please.

**Comment by ch3thanhs** [comment]
Hi @jamie-mh, Can we keep the old bird logo as "twitter.png" and add the new one as "x.png"? So that people who prefer the bird logo can keep using it?

**Comment by ch3thanhs** [comment]
Updated.

**Comment by jamie-mh** [comment]
Thanks!

**Pull request merged**
