### PR TITLE
Added Retrospring icon

### PR DESCRIPTION
**Pull request by MagicLike**
Retrospring is a open source question-based social network. It's main server (https://retrospring.net) has currently a Similarweb rank of 100,165.

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @MagicLike ,

Thanks for the icon. Can you please add an icon without a background or with rounded corners ? It would look a little nicer.

Cheers

**Comment by MagicLike** [comment]
> Hi @MagicLike ,
> 
> Thanks for the icon. Can you please add an icon without a background or with rounded corners ? It would look a little nicer.
> 
> Cheers

Updated! - Better now?

**Comment by jamie-mh** [comment]
Thanks for updating the icon. Can you make it 128x128, please ?

Cheers

**Comment by MagicLike** [comment]
Oops, forgot that - done :+1:

**Comment by jamie-mh** [comment]
Thanks!

**Pull request merged**
