### PR TITLE
Added Peertube icon

### PR DESCRIPTION
**Pull request by MagicLike**
Another federated service where there are multiple servers.

### CODE REVIEW

**Comment by jamie-mh** [comment]
Same as #555, icons must be png.
Thanks

**Comment by jamie-mh** [comment]
Hi @MagicLike ,

Sorry for the slow reply. Thanks it is now a png, however it needs a transparent background. The current icon has a white background. Can you change this please?

Thanks

**Comment by MagicLike** [comment]
> Hi @MagicLike ,
> 
> Sorry for the slow reply. Thanks it is now a png, however it needs a transparent background. The current icon has a white background. Can you change this please?
> 
> Thanks

Should be fixed...

**Comment by MagicLike** [comment]
ughhhh...

**Comment by MagicLike** [comment]
> Thanks for updating the icon. Sorry though, it's not quite right, the middle triangle shouldn't be black. See attached.

what do you suggest? - The icon is normally black in the middle...

**Comment by MagicLike** [comment]
> Thanks for updating the icon. Sorry though, it's not quite right, the middle triangle shouldn't be black. See attached.

Dunno, what happened there... - Is it better now?

**Comment by jamie-mh** [comment]
Thanks! Looks good.

**Pull request merged**
