### PR TITLE
Added 39 more logos

### PR DESCRIPTION
**Pull request by l-marchesi**
Hi Jamie

I added 39 more logos:
- Bunny.net
- Bugcrowd
- Bunny.net
- Cointiger
- Cyon
- Databox
- Hootsuite
- Intigrity
- IT Glue
- Jelastic
- Kaspersky
- LiChess
- LiteBit
- MaiCoin
- Mail.com
- Mailfence
- MathWorks
- mLab
- Monday.com
- Moqups
- NuGet
- nulab
- Oculus
- Plurk
- QNAP
- Sanebox
- SAPO Mail
- Socialbakers
- Sourceforge
- SproutSocial
- SquareSpace
- StatusMail
- Surfshark
- Ting
- Toodledo
- Twilio
- Unbounce
- UpWork
- YoYo Games

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @l-marchesi ,

Thanks for working on all these icons. Just a few comments:
- Is there a need for a dark variant of the Buildkite icon? It seems like the light variant would suffice.
- The Bunny.net icon is a duplicate, it's called "bunnycdn".
- The Cyon icon has an unnecessary background, please revise with the attached icon.
- As per the [Hootsuite brand guidelines](https://hootsuite.widencollective.com/portals/bafpk5oo/MediaKitAssets/c/d53b0c1c-e4e6-4638-b169-251aca64b813), please use the outlined icon rather than the solid icon for the dark variant.
- From the Kaspersky, Moqups and Nulab icons, please remove the solid background. Give the text the current background colour.
- Please remove the text from the SaneBox icon.
- The background on the Plurk icon is redundant, please revise with the attached icon.

Thanks

cyon
plurk

**Comment by l-marchesi** [comment]
Hi @jamie-mh 

- According to the Buildkite brand guideline, they prefer to have other colors in the dark variant: https://buildkite.com/brand-assets
- "Bunny.net" was still on the list - I removed my logo and crossed it off the list :)
- cyon logo is replaced
- Hootsuite logo is replaced
- Kaspersky, moqups and nulab edited
- Sanebox text removed
- Splurk icon replaced

**Comment by jamie-mh** [comment]
Ok, for the Buildkite icon then.
Great work. Thanks a lot.

**Comment by l-marchesi** [comment]
You're welcome, thank you for the review  and your work :)

**Pull request merged**
