### PR TITLE
Add 3 icons

### PR DESCRIPTION
**Pull request by JotaOdiceu**
Added:
- BingX (One of the largest crypto exchanges)
- Brevo (Formerly Sendinblue)
- D4Sign (The largest digital signature platform in Brazil)

### CODE REVIEW

**Comment by Kvasenok** [comment]
Can I suggest using this file for BingX? It's a bit optimized, less jagged, less the size.
bingx

**Comment by JotaOdiceu** [comment]
Awesome! Thanks @Kvasenok

**Comment by jamie-mh** [comment]
Hi @JotaOdiceu ,

Is this still a draft, or can it be merged?

Thanks

**Comment by JotaOdiceu** [comment]
Hi @jamie-mh,

can be merged 🚀

**Comment by jamie-mh** [comment]
Thanks!

**Pull request merged**
