### PR TITLE
Icons for ifirma.pl, wykop.pl and allegro.pl

### PR DESCRIPTION
**Pull request by kwiateusz**
Hi,

Icons are for

- [ifirma.pl](ifirma.pl) - polish accounting company
- [wykop.pl](wykop.pl) - polish analouge of reddit
- [allegro.pl](allegro.pl) - polish analouge of ebay

### CODE REVIEW

**Comment by kwiateusz** [comment]
What's is wrong? Contribution guide says that icons should be in **AuthenticatorPro.Shared/Resources** but **Resources** folder is missing so I assumed that **AuthenticatorPro.Droid.Shared/Resources**  will be better place

**Comment by jamie-mh** [comment]
Hi,

Thanks for contributing.
You haven't made a mistake, the doc was wrong. I've fixed it.

**Comment by kwiateusz** [comment]
@jamie-mh one last question, new assets in AuthenticatorPro.Droid.Shared.csproj should show automatically if contributor uses Visual Studio? I made all changes in normal text editor and I think that was a problem. Maybe in guide should be info about it?

**Comment by jamie-mh** [comment]
Yes, if you add the icons with Visual Studio, they are automatically added to the csproj file. Adding them using a text editor works fine too. Since most people don't have Visual Studio + Xamarin installed, I don't include that step because when I'm testing the icons, I can add them to the csproj rather quickly.

**Pull request merged**
