### PR TITLE
Rebrand assets, new Icon, slightly changed app colours, updated readme, & 2 new icons.

### PR DESCRIPTION
**Pull request by RobertHarnett**
Hello again, sorry I've been busy with life, hence the delay.  I'll break this up starting with the minor changes down to the more subjective changes.

## 2 New Icons
-  bugzilla@mozilla
-  Ente (+ Dark Mode)

Issues #515 and #519 can be closed.

## Updated README.md
- Added header image
- Updated 'Get It On' buttons to new logos and equal padding around each image
- Updated 'Buy Me A Coffee' button to also have equal padding to be the same size.
- Minor changes to the layout such as slightly changed 'Features' format to increase readability. If you want to preview it you can look at a [live version on my fork](https://github.com/RobertHarnett/AuthenticatorPro)

## Ever so slightly changed 'colorLightBluePrimary' within the app to match updated branding
 It's changed from #40C4FF to #2CB1EC. Old colour on the left, new colour on the right.
colours

## Updated app icons
I have updated the app icon and all the necessary scales within the *AuthenticatorPro.Droid/Resources/mipmap folders* and the *AuthenticatorPro.WearOS/Resources/mipmap folders*.

## Rebranding Assets
And finally I have added all the updated assets I feel you might like, again these don't have to be set in stone, if there's, anything you want differently then don't hesitate to ask. For now they are within the directory *doc/Rebranding/*. I have also done a correctly scaled Playstore icon and Feature graphic. The idea is to have the 'showcase_image' be the first screenshot image on the Playstore followed by any order of the regular screenshots that you prefer. 

One emission is WearOS. I couldn't get the emulator to play nicely and get codes added, that's why in the rebranding folder there's a couple unused assets involving WearOS. If you want to use them then just let me know and send me some high res wearOS screenshot.

Without further ado:

wordmark

showcase image

FreeDark ModeCustomizationBackupPermissionSort

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @RobertHarnett ,

Thanks again for your contributions, they are always appreciated.
These are some really nice changes, looks very neat and professional. Well done!

One minor nitpick is that the `ic_launcher` icon could perhaps do with a little more padding around the edges due to the way adaptive icons work on Android. Also, there is perhaps a little too much space between sections in the readme :)

I can provide some high-quality Wear OS screenshots if you'd like, just let me know what you think they should showcase.

Cheers again, and let me know your thoughts!

**Comment by RobertHarnett** [comment]
Yeah I agree I might have got a little carried away with the padding on the readme :P It's fixed.

Regarding the app icon, I actually thought thought the same, but I went back and checked, and the icons actually fall within the key lines. I used the android asset studio to generate the icons... See for yourself.
My Application  C__Users_hello_AndroidStudioProjects_MyApplication2  – MainActivity kt  My_Application app main  27_09_2022 17_15_38

**Comment by marcusbillman** [comment]
Hi @RobertHarnett!

I just happened to come across this pull request and as a UX designer, I'll say these images look great! They feel fresh and showcase the app in a clearer way.

I've got a few nitpicks regarding the copywriting, though:
- Can you change "No In app purchases" into "No in-app purchases" (based on the correct spelling from [Google themselves](https://support.google.com/googleplay/answer/1061913?hl=en))?
- "Backup and restore" should be "Back up and restore" when used in verb form ([quick explainer](https://brians.wsu.edu/2016/05/19/backup-back-up/)). I know this error is present in the app as well, so maybe this should be corrected there too. @jamie-mh
- I noticed the current Google Play screenshots use British spelling (e.g. *categorise*) whereas these new images are American (e.g. *customize colors*). That might be totally fine, but I thought I'd mention it in case you want to keep more consistency.

I know these are tiny details, but things like these add up when making a polished product! Nonetheless, great work!

**Comment by jamie-mh** [comment]
Hi everyone,

@RobertHarnett ,
Thanks for the readme change.
Here are some Wear OS screenshots with the updated blue:

Screenshot_20221002_101720Screenshot_20221002_101748
Screenshot_20221002_101938Screenshot_20221002_102009
Screenshot_20221002_102407Screenshot_20221002_102446

No problem for the app icon, you were way ahead of me and made sure that the icon was in the safe zone.

Thanks, @marcusbillman for your feedback. I agree that we should make the writing as consistent as possible.
Most of the strings in the app use British spelling, we can update the app to use American spelling or update the material to be consistent with the app. I'm not sure what the best approach is here.

+1 for the difference between back up and backup. I'll update the app strings to reflect this.

Cheers

**Review by MagicLike — COMMENTED** [review]
There are a few things I noticed:
- The "Buy me a coffee" button looks blurry now (at least for me)
- The sentence "No app permissions required, everything on the device." is not nice to read, Maybe something like "[...] everything is (saved) on the device. Also this statement is not 100 % correct, the camera permission is needed to scan QR-codes.
- The words "Reorder", "search" and "categorize" should be colored blue for consistency and I am not shure if the word "codes" is the right term in that situation. I'd rather write "accounts" there, because the account entries output the codes.

**Comment by RobertHarnett** [comment]
@marcusbillman thanks for the suggestions they are great! I have updated the spelling to British English to match the rest of the project, I'll admit being British myself I'm biased to this 😜, I had just assumed the project was US-en.  I have also updated the other grammatical changes you noted. 

@jamie-mh Thanks for those! I have added a WearOS graphic now.

@MagicLike I have had a look at the "Buy me a coffee" button and the raw image file seems fine. I thought it might be a scaling issue with the readme file adjusting the height of the image but that isn't the case. It's the same height as playstore button and are both rendered at the same scaling. I'd suggest we just ignore it for now, complete the merge and if the issue still persists, I'll take another look. 

Regarding the "No app permissions required, everything on the device.". It is technically correct, the app doesn't require the camera permission to work, while it's optional, it's not a necessity to the functioning of the app. 

While the app also does technically use permissions such as run-in background, in this case it's referring to [run time permissions](https://developer.android.com/guide/topics/permissions/overview#runtime). These are what most users are familiar with and think about when talking about app permissions. Run-time permissions are also what are shown on a device when you look at an app's permissions in the device settings. I don't think this is us obfuscating or lying to users about the permissions used and I'm happy to keep it how it is.

I too your suggestion to update the readme app description to be smaller.

**Comment by jamie-mh** [comment]
Hi @RobertHarnett ,

Thanks for the changes! Everything looks great, I'll merge.

Cheers

**Comment by MagicLike** [comment]
@jamie-mh The images / assets on the App page in @IzzySoft 's F-Droid Repo aren't updated yet...

**Comment by IzzySoft** [comment]
Fastlane should be pulled along whenever a new update was detected. Currently, `full_description.txt` is excluded here due to some formatting issues (the double-lines would be formatted as a single paragraph each when handled as Markdown – and would not look that nice when dealt with as plain-text; let me know if you want me to ignore that, or when the formatting was updated).

What are you missing, @MagicLike? You write "screenshots", but they are there (I only pull `phoneScreenshots`, so the others are not pulled).

**Comment by MagicLike** [comment]
> What are you missing, @MagicLike? You write "screenshots", but they are there (I only pull `phoneScreenshots`, so the others are not pulled).

Yes, the screenshots are there, but these are old ones. Above @RobertHarnett  updated these and made a redesign. The only asset, that updated in the repo is the icon...

**Comment by IzzySoft** [comment]
And you're sure the screenshots have been updated in Fastlane [here](https://github.com/jamie-mh/AuthenticatorPro/tree/master/fastlane/metadata/android/en-US/images)? Their timestamp says "last updated 2 years ago". So if they're not updated here, they won't reach my repo either :wink:

**Comment by MagicLike** [comment]
> And you're sure the screenshots have been updated in Fastlane [here](https://github.com/jamie-mh/AuthenticatorPro/tree/master/fastlane/metadata/android/en-US/images)? Their timestamp says "last updated 2 years ago". So if they're not updated here, they won't reach my repo either :wink: 

Yeah, that's why I mentioned @jamie-mh to point that out... (Perhaps it was a little badly worded)

**Comment by IzzySoft** [comment]
Feel free to give me a ping once there're there – in case the next release is too far in the future to wait for it, I can trigger a "fastlane update" manually then.

**Comment by MagicLike** [comment]
> Feel free to give me a ping once there're there – in case the next release is too far in the future to wait for it, I can trigger a "fastlane update" manually then.

@IzzySoft I created a PR draft for the fastlane update (#576)

**Comment by IzzySoft** [comment]
Thanks! Though I hate "framed" screenshots. Wastes too much valuable screen estate on small screens, making it difficult to see details :man_shrugging: Maybe you want to update `full_description.txt` as well (see my hints there)?

**Pull request merged**
