### PR TITLE
Added Unraid icon

### PR DESCRIPTION
**Pull request by MagicLike**
The Unraid Icon can be used for their [forums](https://forums.unraid.net) and for services hosted on a Unraid server, so the Similarweb score can' t apply here.

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @MagicLike ,

Thanks for contributing. According to the [icon guidelines](https://github.com/jamie-mh/AuthenticatorPro/blob/master/CONTRIBUTING.md), icons must be 128x128 png files.
Can you update it please ?

Cheers

**Comment by jamie-mh** [comment]
Hi,

Can you use an icon without a background / frame, such as the icon that you used initially, except as a png file.

Thanks

**Comment by MagicLike** [comment]
> Can you use an icon without a background / frame, such as the icon that you used initially, except as a png file.

The problem is, that the .png wouldn't be a square... - when I want a png with 128px in width, I get 74px in height.

**Comment by MagicLike** [comment]
> Hi,
> 
> Can you use an icon without a background / frame, such as the icon that you used initially, except as a png file.
> 
> Thanks

It should be ok now! 👍

**Comment by jamie-mh** [comment]
Looks good. Thanks!

**Pull request merged**
