### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by b3pio**

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @b3pio ,

Thanks for your contribution.
Just a couple of comments:

- You've changed the Cryptocom icon, is there a reason? I would prefer to keep the old one.
- I don't think the Escape From Tarkov icon is very readable. I might be better to have a fully white version for the dark theme and a fully black version for the light theme.

**Comment by b3pio** [comment]
No problems,

- Crypto.com icon is an updated version to reflect their icon used for the app(s) and also on their website. Current icon is still relevant, so I will let you decide.
- EFT icon I can re-work it so its clearer, it was just the best one I could find from them at the time.

I plan to continue to keep contributing with more in the future.

**Comment by jamie-mh** [comment]
Ok, it's probably best to use the newer Crypto.com icon then.
I agree that there aren't very many high quality icons for Escape From Tarkov, perhaps this one would work better: [https://fr.wikipedia.org/wiki/Fichier:Escape-from-tarkov.png](https://fr.wikipedia.org/wiki/Fichier:Escape-from-tarkov.png)

**Comment by b3pio** [comment]
Have uploaded a different EFT icon, let me know what you think. The original logo just wouldn't seem to look good on its own which ever way I layout it up so I tried something different, hopefully it doesn't come out too small and unreadable.

**Comment by jamie-mh** [comment]
I'm not a fan of that icon because it's not an official one, we might not have permission to use it.
Here's my attempt at an icon, the text is a little small but it's readable on my device.

escapefromtarkov
Screenshot_1632060008

Let me know if you think this would work.

**Comment by b3pio** [comment]
I like the idea you had and looks good when mocked up small on the actual app screen so I refined it more with the official EFT text and made a dark version as well. Hopefully that works !!

**Comment by jamie-mh** [comment]
Thanks great, thanks. I'll merge.

**Pull request merged**
