### PR TITLE
Updated icons + localization

### PR DESCRIPTION
**Pull request by luaxlab**
Hello there,

As said in #35 I took some time to update the Icons for an uniform style. Using secret ninja techniques (image optimization) I was able to free 1.1MB from the xxxhdpi and xxhdpi drawables. I didn't see big improvements on <xxhdpi drawables so I did not do any optimzation there.

I additionally updated the german localization files because.... they sounded strange....

Cheers

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @luaxlab ,

Thanks for working on the icons.
There are just a few things that I'm not so sure about:
- I don't know what the usage rights of the Mario character are for the Nintendo icon. Is it copyrighted?
- The dark Patreon icon would look nicer with and orange circle perhaps.
- The Samsung icon doesn't seem particularly recognisable. I understand that the old one was a little small but the 'S' seems a little generic.
- The old Stripe icon except with rounded corners might be a better fit (such as the favicon on their website).
- JetBrains state that their logo should have the coloured beams around it (https://www.jetbrains.com/company/brand/). I'm not sure what to think about this.
- Please indent the strings.xml with 4 spaces instead of 2.
- Is the disclaimer at the top of strings.xml necessary? I'm the only person developing features for the app, if there is an issue with translation, it's not a problem if you contact me and let me know :)

I'd like to know your thoughts about this stuff.

**Comment by luaxlab** [comment]
Hello @jamie-mh 

I think that I'd be a good Idea to get in contact with Nintendo and JetBrains about this, I'm sure there will be no problem (the nintendo logo is trademarked as well?).

I'll replace the stripe Icon with an round-corner one.

For the Samsung Icons I have got two ideas:
- Adding the [Samung Electronics Global Logo](https://www.samsung.com/etc.clientlibs/samsung/clientlibs/consumer/global/clientlib-common/resources/images/global-samsung-logo.svg)
- Adding the above logo, but adding a line break "sam**\n**sung"

I think the first one is the better choice.


I dont know how those intents got messed up but I'll fix that.

I didn't mean to offend you in any way. I tought that there may be some times when others contribute code.
I think I'll remove those, or move those to a contribute.md, leaving only the locale specific notes for future translators.


Can you agree with me about this?

**Comment by jamie-mh** [comment]
Hi @luaxlab ,

I'm not an expert in copyright/trademark law, but as I understand it, the use of a logo in this context is permissible. However, the use of a copyrighted work (eg: Mario) is unclear. Nintendo are quite protective of their IP so I really don't know how they will respond. To be safe, why not use the Nintendo logo without the red frame.

How about using the first logo on this page https://www.jetbrains.com/company/brand/logos/ for both light and dark themes. The JetBrains logo might look nicer with some colour.

For the Samsung logo, in my opinion, the old one with the blue oval shape around it seems more easily recognisable than a purely text one. I personally find the icons with text that stands out too much don't look as good as ones with more shapes and colours.

And don't worry, no offence taken. The notice seemed a little out of place, that is all.

Thanks

**Comment by luaxlab** [comment]
Hi @jamie-mh 
I'll rollback the icons.
May I add the Samsung without blue as "samsung2" or "samsungalt" (like money2).

**Comment by jamie-mh** [comment]
Sure, 'samsung2' is good.

**Comment by luaxlab** [comment]
Hi @jamie-mh,

I've made all the changed, please take a look.

**Comment by jamie-mh** [comment]
Everything looks good. I'll merge. Thanks again.

**Pull request merged**
