### PR TITLE
Added 10 new Icons + updated missing_icons.txt

### PR DESCRIPTION
**Pull request by b3pio**

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @b3pio ,

Thanks for the icons. The icons look good, however a few of them have unnecessary backgrounds. 
Please rework them with the following transparent images:

cryptonator
crypton
credly
playbread

**Comment by b3pio** [comment]
Ok I can fix and update shortly. Also planning to do many more soon.

**Comment by b3pio** [comment]
Added an additional 3 icons.

**Comment by jamie-mh** [comment]
Looks great! Thanks.

**Pull request merged**
