### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by LarsK1**
I added new icons for:

- discogs
- invoice ninja
- itch.io
- matomo
- telnxy
- ultimaker
- updraft
- wordfence

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @LarsK1 ,

Thanks for contributing. A few tweaks are needed:

- The Ultimaker, Updraft and Wordfence icons must have a transparent background. They're white currently.
- The Telnyx icon must fill as much space as possible in the image.
- The Invoice Ninja icon has an unnecessary background, it can be removed. It also needs a dark theme variant.
- The Discogs icon is too complex, please use the simplified vinyl mark as per the [brand guidelines](https://www.discogs.com/brand) (attached). It also needs a dark theme variant.

discogs logo simplified

**Comment by LarsK1** [comment]
@jamie-mh added the requested changes, except for invoiceninja as there currently doesn't exit one ...

**Comment by LarsK1** [comment]
please merge

**Comment by jamie-mh** [comment]
Thanks for the changes.
I will create a dark variant of the Invoice Ninja icon.

**Comment by LarsK1** [comment]
@jamie-mh when will the next release probably be?

**Comment by jamie-mh** [comment]
I don't really have a schedule. The app needs to be thoroughly tested before a release, which takes time.

**Pull request merged**
