### PR TITLE
Added 23 new icons + Updated 41 icons

### PR DESCRIPTION
**Pull request by Kvasenok**
I'm sorry for so many PR's, this should be the last.

This PR covers some of 2FA Directory's [Gaming](https://2fa.directory/int/#gaming), IoT, Security and Social categories within SimilarWeb's top 200k. This is also a big update of the existing icons. Looks like I'm following in @RobertHarnett 's footsteps. 

Added:
1. Aternos
2. Capcom ID (named just capcom.png)
3. CheckMateGaming (called CMG, but named "checkmategaming.png" according to the url) (+ Dark Mode)
4. DMM (+ Dark Mode)
5. Eneba
6. ESL Play (+Dark Mode)
7. GameMaker (+ Dark Mode)
8. Modrinth
9. Ajax.systems (+Dark Mode)
10. Particle.io
11. Raspberry Pi
12. AVG
13. Norton (+ Dark Mode)
14. IronVest (+ Dark Mode)
15. AllMyLinks
16. Emplifi
17. LIHKG
18. Ink.bio
19. Newgrounds
20. SpaceHey
21. Wise
22. Prey (+ Dark Mode)
23. Pachca (+ Dark Mode)

Updated:
1. Unity (Totally missed their rebranding)
2. Razer (Black&Green instead of just green)
3. Ubiquiti (New icon)
4. Dreamhost (Updated colors + added Dark Mode)
5. Pixiv (It was actually added 3 weeks ago and is not released yet, but since it's been requested I replaced it with P icon, trying to avoid full-word icons if possible)
6. Netlify (New icon + added Dark Mode)
7. Fastmail (added Dark Mode)
8. Hootsuite (New icon + removed Dark Mode)
9. Zapier (New icon)
10. Zoom (New icon)
11. Ultimaker (New icon)
12. Activision (New icon based on favicon, should look better)
13. Mega (Made "M" white instead of transparent)
14. Wax (Removed "TM", dark mode icon is now white instead of grey)
15. AscendEX (Updated colors + added Dark Mode) (I replaced it with multi-colored icon according to their branding, used [these](https://images.app.goo.gl/GQXuxfpBjEuppU7C7) colors for dark mode)
16. StartMail Dark Mode (Updated colors Inspired by [this](https://loghi-famosi.com/startmail-logo/) article)
17. Satoshi Tango (New icon)
18. SimpleLoging (New icon)
19. Telnyx (New icon)
20. Practice Better (New icon)
21. Webflow (Removed background)
22. Zoho (New icon)
23. Migros (Looks like previous update of this icon was meant to fix margins, but replaced the icon instead. Fixed.)
24. Ledn.io (New icon + Added Dark Mode)
25. Koofr (New icon)
26. Gate.io (New icon)
27. Fanduel (Based on the icon itself there is a typo, the icon is named "fanduAl" instead of "fanduEl". Added under correct name.)
28. Electronic Arts (Updated colors)
29. Cachet (New icon)
30. Algolia (New icon)
31. Docker (Updated colors)
32. Cronometer (New icon)
33. Chargebee (New icon)
34. Txbit (Completely removed this icon. The platform is now officially closed.)
35. Buildkite (Removed Dark Mode. The dark icon is basically the same as the normal one. I don't know why it's here in the first place.)
36. Zyxel (Replaced with green icon because 2fa is part of Zyxel Networks, they have green X icon + revomed Dark Mode)
37. Capsule CRM (Updated colors - Replaced black with brand color)
38. HelloSign -> Dropbox Sign (Rebranding. Removed "hellosign.png", added new icons "dropboxsign.png" and "dropboxsign_dark.png" for dark mode)
39. Coinjar (New icon + Removed Dark Mode)
40. Origin (Completely removed this icon. Origin is replaced by EA Play/App, EA icon should be used instead)
41. Bethesda (Fixed wrong icon + Added Dark Mode)

Extra icons:
1. Xbox (Replaced black and white icons with a single green icon)

### CODE REVIEW

**Comment by OmarNazzal150** [comment]
I got them from the 2fa directory social category. I got 9 icons from the social category

https://2fa.directory/int/#social

https://emplifi.io/
https://eclincher.com/
https://allmylinks.com/
https://lobste.rs/
https://lnk.bio/
https://lihkg.com/category/1
https://spacehey.com/
https://www.pixiv.net/en/
https://www.newgrounds.com/

**Comment by Kvasenok** [comment]
@OmarNazzal150 Again, some of these services are not within Similarweb's Top 200k Ranking. Please check the [Contribution Guide](https://github.com/jamie-mh/AuthenticatorPro/blob/master/CONTRIBUTING.md) before asking for every service you can find on 2FA Directory. Thank you.

**Comment by OmarNazzal150** [comment]
Here are the Similarweb websites 

https://www.similarweb.com/website/lnk.bio/#overview

https://www.similarweb.com/website/lihkg.com/#overview

https://www.similarweb.com/website/spacehey.com/#overview

https://www.similarweb.com/website/pixiv.net/#overview

https://www.similarweb.com/website/newgrounds.com/#overview

https://www.similarweb.com/website/eclincher.com/#overview

https://www.similarweb.com/website/emplifi.io/#overview

https://www.similarweb.com/website/lobste.rs/#overview

https://www.similarweb.com/website/allmylinks.com/#overview

**Comment by Kvasenok** [comment]
@OmarNazzal150 Eclincher is 444k global rank, lobste.rs is 245k global rank

**Comment by OmarNazzal150** [comment]
So you will only add 2 icons except for the rest

**Comment by Kvasenok** [comment]
@OmarNazzal150 I definitely will NOT add these 2 icons because they are ABOVE 200k global rank and they should be BELOW 200k to be added.
As for the rest of the icons, I'm maybe add some, but I'm not sure about all of them.

P.S. You know, instead if requesting dozens of new icon you could check if any of the existing icons needs updating, because I've found about a dozen and I still keep finding more outdated icons. It's just a thought.

**Comment by OmarNazzal150** [comment]
Oh, I'm sorry. Next time, I will add icons that are below 200k Global World on Similarweb

**Comment by Kvasenok** [comment]
Ok, I've added the icons and edited this PR accordingly. It should be ready to merge.

**Comment by Kvasenok** [comment]
Ok, I'm done, for real this time. I don't have anything new to add or update. This PR is already too big and worth an update.
@jamie-mh Ready to merge

**Comment by Kvasenok** [comment]
I'm nitpicking at this point :)

**Comment by Kvasenok** [comment]
Ok, I've checked every exesting icon and updated the ones that needed it. All the details are in the first comment. Now this PR definetely worth the AP's update.
@jamie-mh Ready to be merged

**Comment by Kvasenok** [comment]
Ok, I've checked every existing icon and updated the ones that needed it. All the details are in the first comment or in commit comments. Now this PR definetely worth the AP's update.
@jamie-mh Ready to be merged

**Comment by Kvasenok** [comment]
Ok, I've checked every existing icon and updated the ones that needed it. All the details are in the first comment or in commit comments. Now this PR definetely worth the AP's update.
@jamie-mh Ready to be merged

**Comment by Kvasenok** [comment]
Somebody stop me

**Comment by jamie-mh** [comment]
Hi @Kvasenok ,

Thanks for the new icons and updating the current icons. It's hard to keep up with all the changing logos!
This is great work, I don't have any comments. Everything looks good.

I'll merge this now.

**Comment by OmarNazzal150** [comment]
Finally I've been waiting for this like a month. Now Jmh. Added those icons. Good job Jmh. Keep up the good work 💪💼👍

**Comment by Kvasenok** [comment]
Great. I add a bunch of icons, this dude comes to this PR requesting more icons without trying to adhare to the contribution guidelines, I check every requested icon for complience with guidelines, add every requested icon and this is what he says.
@OmarNazzal150 you, sir, are an unpleasant person.

**Comment by OmarNazzal150** [comment]
Kvasenok. Why did you say that to me. I'm just requesting some icons in the future. So we can have an huge icon library. And I followed the icon guidelines. And I will be good next time.

**Comment by Kvasenok** [comment]
@OmarNazzal150 forget it, man. No more icons for you from me though. Good luck!

**Comment by OmarNazzal150** [comment]
☹️. Okay then no more icon requests for the rest of my life

**Comment by Kvasenok** [comment]
@OmarNazzal150 you can add the icons yourself by creating a PR, like I did, instead of requesting them.

**Comment by OmarNazzal150** [comment]
I'm using Mobile. Not desktop. I can't do that

**Comment by OmarNazzal150** [comment]
Okay I guess I will do it. Like just you did. 2 weeks ago

**Comment by Kvasenok** [comment]
@OmarNazzal150 you can DM me and I'll give you links to a few online editors I used to edit icons, so you could do it on mobile. FYI I edited most of these icons on my phone, not on desktop.

**Comment by OmarNazzal150** [comment]
I will just use the web version of GitHub on my phone. And creating pull requests in the Future. If I wanted

**Comment by Kvasenok** [comment]
@OmarNazzal150 up to you. If you need any help with editing, just say the word.

**Comment by OmarNazzal150** [comment]
Okay. Thanks. I understand what you said. 😊🥰

**Pull request merged**
