### PR TITLE
Added missing logos

### PR DESCRIPTION
**Pull request by l-marchesi**
Added logos for:
- [digitec](https://digitec.ch)
- [galaxus](https://galaxus.ch)
- [Migros](https://migros.ch)
- [FastMail](https://www.fastmail.com)
- [FloatPlane](https://www.floatplane.com)
- [infomaniak](https://www.infomaniak.com)
- [invision](https://www.invisionapp.com)
- [meistertask](https://www.meistertask.com)
- [Microsoft To-Do](https://todo.microsoft.com)

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @l-marchesi ,

Thanks for your contribution.
Just a couple of comments:

- Please revise the Floatplane logo, the image is too large and shouldn't have a background. Use the light blue colour shown here: [https://facebook.com/FloatplaneMedia](https://facebook.com/FloatplaneMedia)
- The Galaxus icon should fill the image and needs a dark mode variant

**Comment by l-marchesi** [comment]
Hi @jamie-mh 

Thank you for your feedback, I will take care of it tonight or tomorrow 👍🏻

**Comment by l-marchesi** [comment]
Hi @jamie-mh 
I worked on the icons according to your comments. Could you please review it again?
Thank you :)

**Comment by jamie-mh** [comment]
Thanks, everything looks good.

**Pull request merged**
