### PR TITLE
A few new icons 2023-02-18

### PR DESCRIPTION
**Pull request by NebularNerd**
A few new icons for 2FA's I use

- governmentgateway is a rename of govuk, this reflects the correct 2FA name
- spring is the new name and logo for TeeSpring
- Klarna may have a different 2FA name if you are a customer, this is the name for their merchant portal.
- plarium comes from their .svg, the original is not a solid black hence the invert is not solid white.

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @NebularNerd ,

Thanks for contributing these icons. Can you please make a few changes to your PR?

**Naming**:

- Rename `admitadcom` to `admitad`
- Rename `idg2a` to `g2a`
- Rename `klarnamerchantportaleu` to `klarna`

**Eligibility**:

- The Government Gateway icon is redundant since there is already a `govuk` icon. Most people will recognise by that name, I believe.
- The `redfoxforum` icon doesn't meet the criteria for an icon (Similarweb < 200k)

**Style**:

- The edges of the Avast and G2A are a little aliased. They could be smoother.
- The Klarna logo is better with the dot at the end, like on their website. See attached.
- The `plarium` icon should be solid white, like on their website.
- The `vogons` icon is tiny. It would be nicer to use something similar to the favicon on the website. I've attached my admittedly not brilliant attempt at extracting the icon, if you can get your hands on the source files, that would be even better.

Cheers

Klarna_Logo_black
vogons_dark
vogons

**Comment by NebularNerd** [comment]
Hi @jamie-mh,

No problem, let me see what I can do. The Plarium icon actually comes from their svg, the black is not solid black but rather a very subtle gradient, when I inverted it that was the 'correct' inversion, but I can make it white white no problem. 🙂

I'll sort those other changes as well, can I update this PR or do I need to kill it and create a new one?

**Comment by jamie-mh** [comment]
Thanks. You can update your fork and changes will be reflected here. No need to create a new PR.

**Comment by NebularNerd** [comment]
New versions of all but vogons uploaded, just waiting to see if they can supply a better icon. If not I could split their existing one in two to make a square icon.

**Comment by jamie-mh** [comment]
Thanks. Changes look great so far.

**Comment by jamie-mh** [comment]
I'm going to merge this for now. Thanks.

**Comment by NebularNerd** [comment]
I'm still waiting on Vogons for a reply, so I was going to suggest this. I'll do a seperate PR for them later 🙂

**Pull request merged**
