### PR TITLE
add bitvavo icon resolve #525

### LINKED ISSUE #525: Icon Request: Bitvavo
**Bitvavo**
https://bitvavo.com

https://bitvavo.com/press/blue/bitvavo-mark-square/bitvavo-mark-square-blue.png

They sometimes use a different color for their logo (blue vs. black on the website), but the Android App Icon is actually blue.

Thanks in advance!

### PR DESCRIPTION
**Pull request by kwiateusz**

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @kwiateusz ,

Thanks for contributing.
As per the icon guidelines, can you please use an icon without a background, such as the favicon on their website (attached).

favicon

Cheers

**Comment by kwiateusz** [comment]
I havent checked it before, sorry. 

But looking into their [brand book](https://www.behance.net/gallery/125625687/Bitvavo-Brand-Guidelines) it stays that app logo should be white on blue background but with rounded corners. Or If we want to use page logo it should be white or black without background. So our both logos are wrong :D 

What you think which we shold use? App or page logo?

**Comment by jamie-mh** [comment]
Hi,

Technically, that document is more of a brand suggestion rather than a guideline.
I think we should use the logomark with the two lines without a background.

We can use a black and white or blue version. I personally prefer the blue version, as we won't need a dark variant :)

Thanks

**Comment by kwiateusz** [comment]
As you wish, new logo arrived :)

**Comment by jamie-mh** [comment]
Nice. Thanks!

**Pull request merged**
