### PR TITLE
Update icon for Home Assistant + change Huobi to HTX

### PR DESCRIPTION
**Pull request by Kvasenok**
Home Assistant updated its design and logo. 
Additional information on the new logo here: https://design.home-assistant.io/#brand/logo
Updated the icon accordingly.

### CODE REVIEW

**Comment by Kvasenok** [comment]
Huobi icon update was supposed to be a separate PR, my bad, pressed the wrong button.

**Comment by Kvasenok** [comment]
Also, Huobi recently changed its name to HTX. Should the icon(s) still be called huobi? I mean, they didn't charge the logo itself, just the name.

**Comment by jamie-mh** [comment]
Hi @Kvasenok ,

Thanks for the icons!
Yes, you can rename the Huobi icon to HTX in your PR, that's not a problem.

Cheers

**Comment by Kvasenok** [comment]
Hi @jamie-mh ,
Thanks for reviewing.
I'm not good at GitHub yet. Is this way of renaming fine?

**Comment by jamie-mh** [comment]
Yes, that's fine. Thanks!

**Pull request merged**
