### PR TITLE
Updated 56 icons + 1 new icon + Suggestions 

### PR DESCRIPTION
**Pull request by Kvasenok**
This PR mostly focuses on updating icon colors and dark mode icons, but also includes some new icons and rebrandings.

# Updated
1. **1Password** (Updated icon + Added Dark Mode. The old icon is now exclusive to the app and 2fa is a part of the whole account hence the brand icon.)
2. **Admitad** (Updated colors)
3. **Airship** (Updated icon. They use it both in the main logo and in the favicon)
4. **Auth0** (New icon + Added Dark Mode. I just added it and they already have a new icon.)
5. **Automate.io** (Removed icon. It has joined Notion and there is an icon for it.)
6. **Barmenia** (Removed background)
7. **BetVictor** (New icon from SVG + Added Dark Mode icon)
8. **Borgbase** (Added color. I don't see a reason to use black icon when they have colored version. Removed Dark Mode icon.)
9. **Bugsnag** (New icon + Added Dark Mode icon. Colors based on the official logo)
10. **Cake Defi --> Bake** (only renaming, the icon stays the same)
11. **Call of Duty** (New icon. Can't say I think it's better, but it's the official new logo with positioning for a square icon. Alternatively, I've tried to imitate [this icon](https://authenticator.2stable.com/assets/img/2fa-services/Icons/callofduty.com.svg) with the new font and made [this](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/ec53ae01-a451-4120-838f-955dfab0d04c), it's a bit unofficial but might look better in the app. Or we can go further and use the [first letter](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/87694776-d065-4969-9e75-411c10c459e7) as an icon, they do the same for the favicon)
12. **CloudHQ** (just Added Dark Mode. I think it could use a white icon due to bad contrast.)
13. **Control D** (Updated colors on both icons. We can also remove background (circle) entirely and use [this icon](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/6b45735b-9a79-4cfe-b5c2-aece4985f31b) for both modes instead of two, but the look on light backgrounds is debatable)
14. **Coursera** (Removed background. According to their [brand guide](https://about.coursera.org/brand-guide/) they don't mind the use of a blue C without background, but prefer a white icon on dark backgrounds. I didn't add the white icon just because there are many white icons already and the blue looks OK on dark backgrounds)
15. **CrowdIn** (New icon according to their [guidelines](https://support.crowdin.com/using-logo/), I used the small-scale logo to avoid unnecessary background + Added Dark Mode)
16. **Digitec** (Updated colors and margins. It probably could use a dark mode variant similar  to Qnap with red part intact, but the blue part here is a bit brighter and the icon looks pretty good on dark backgrounds, so up to debate, see my P.S.)
17. **Disroot** (Removed background + Added Dark Mode icon)
18. **Ecobee** (Updated icon + Added Dark Mode. I've seen an argument for the icon being too thin, but I think it looks fine with the right colors)
19. **Enpass** (New icon + Added Dark Mode icon. Replaced an app icon with a service logo)
20. **ente.io** (I used a favicon instead of the full logo. Funny enough, they use it in their authenticator app. The colors are based on the logo for light mode and on the actual favicon for dark mode. Alternatively, we can use the new grey dark mode icon as the default icon.)
21. **Epic Games** (only added Dark Mode icon. They never use their default logo on dark backgrounds because the dark-grey shield is hard to see.)
22. **Filen** (Updated Dark Mode icon)
23. **G2A** (Updated icon + Removed Dark Mode icon. Same treatment as ente.io. I think it improves legibility and removes the need for a dark mode icon)
24. **Glassdoor** (New icon)
25. **Heroku** (Updated Dark Mode icon using official colors. Not every dark mode icon has to be white)
26. **Hover** (Replaced text logo with icon)
27. **Infomaniak** (Removed background. Actually, their [press kit](https://www.infomaniak.com/en/about/press#) suggests we should use the old icon, but the new icon I've added is used by 2FA Directory and a few other 2fa catalogs and it fits better into the whole "no background" paradigm of the app. So let's just assume this icon is a letter from the text logo and it is allowed)
28. **Internxt** (Updated icon + Added Dark Mode icon)
29. **Intigriti** (Updated colors. Another option is to keep the current icon and use the new one as a dark mode icon instead of white.)
30. **Lenovo** (I know that I just added it and that our icons are supposed to have transparent background, but in this case the red square is kinda a part of the brand and it looks much better than logomark or a [red L](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/e65404c8-5361-4ec1-a987-ce6522e00dd4))
31. **Mail.com** (Updated icon, removed transparent letter. I'm all for transparacy but this icon should have a white letter inside similar to the facebook, vk, mega etc. icons. If we want a transparant 'm', we must use a white icon for dark mode, but there are enogh white icons already.)
32. **Mimecast** (Updated icon + Added Dark Mode icon)
33. **Ngrok** (Full-text logos replaced with icons, used brand color according to their guidelines)
34. **Notesnook** (only updated Dark Mode. Looks like this icon used negative colors, it made the shadow black. Fixed by recoloring original SVG.)
35. **npm** (Replaced logo with an icon used everywhere. Alternatively we can use [this](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/db22b60c-9328-45b5-ae1a-51479b26ad05) icon, but I think the one I use is more recognizable)
36. **NuGet** (only added Dark Mode icon. The current light mode icon has terrible contrast on dark backgrounds and they seem to use the white icon on dark backgrounds.)
37. **Nulab** (Removed background. I'm not sure about the need for a dark mode variant, but I can add it as part of my P.S. if it gets approved)
38. **NURI** (Removed icon. NURI as a brand doesn't exist anymore)
39. **Okta** (New icons)
40. **Paysafecard** (Removed icon. Based on 2FA Directory and their website they don't seem to support TOTP anymore. Correct me if I'm wrong.)
41. **PeerTube** (Added Dark Mode icon. They don't have an official "white" icon for use on dark backgrounds so I had to recolor the original logo a bit as it was bugging me)
42. **Playbread** (Removed icon. Looks like it was some kinda casino. Out of business)
43. **Privacy.com** (Added Dark Mode icon. It's a b&w icon and it really needs a dark mode version and the only solution I see is reversing the colors)
44. **Pushover** (Removed background. Same reasoning as for Infomaniak. Can be reverted if necessary)
45. **Qnap** (only added Dark Mode icon. The default icon has bad contrast on dark backgrounds and a wierd white outline of the red part. The problem is this new white icon is cut from a PNG icon. Alternatively I can recolor the original SVG, but it will have a black outline of the red part, like [this](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/f61da20c-09bd-493e-9da6-1f63dcf58169))
46. **Salesforce** (Removed text. The text inside icon is unreadable and redundant, don't use the full logo as ab icon, check their website and favicon)
47. **Samsung** (Replaced a text-based logo with a letter-based icon(s), same as for Sony, but used Samsung blue)
48. **Short.io** (I used their logo from their main page, fits better)
49. **Shortcut** (New icon)
50. **Societe Generale** (just Added Dark Mode icon. Without it half of the icon blends into black theme and has bad visibility on dark theme. They deal with it by adding a small white frame for dark backgrounds, so I took it from the official logo.)
51. **Sony** (Replaced a text-based logo with a letter-based icon(s))
52. **Spotify** (Updated colors. As TOTP is supported only by Spotify for Artists, this is the icon for the service. Default green Spotify icon can be added to extra icons if necessary)
53. **TinyURL** (only added Dark Mode, this is the official dark mode icon)
54. **Uber** (Updated icons similar to ngrok, Samsung, Sony, Wyze, ente)
55. **Windscribe** (Updated icon + Added Dark Mode icon)
56. **Wyze** (I used the first letter instead of the full word, similar to the Samsung or Sony icons update, but kept original letter thickness)
57. **Xing** (Updated icon)

I also updated icons for **Ajax Systems**, **Activision**, **JumpCloud** and **HTX** but I didn't count them because it was just a quality update.

# Added
1. **Adyen** (I honestly never used it, but it has good rating on [SimilarWeb](https://www.similarweb.com/website/adyen.com/#overview) and the icon is present in many 2fa icon packs, so I presume many people use this service)

## Extra icons
1. **Apple** (as requested in #1002)
2. **Android** (Since we now have an Apple icon and it's an Android app I thought it would be appropriate to have an Android icon as well. I know there is no "Android TOTP" service, but some users can associate their TOTP provider with Android.)

# P.S.
## Dark Mode suggestions 
I have a few icons that don't really need a dark mode version but could benefit from the functionality. For example, below are a few possible dark mode variants next to the default light mode icons. Since Codeberg has a dark mode variant I thought it was worth a try.

### Bitrix24
This is a dark mode icon for **Bitrix24** using the second main color, see [this logo](https://github.com/jamie-mh/AuthenticatorPro/assets/44749170/53201f07-66f7-4531-800d-734e42a1af26)
bitrix24 bitrix24_dark
Screenshot_20231019_211059_Authenticator Pro
Screenshot_20231019_211013_Authenticator Pro

### Wise
This is a light mode icon for **Wise**, because the current icon was supposed to be a dark mode icon but I compromised. Again, not needed, but would look better.
wise_light wise
Screenshot_20231019_211135_Authenticator Pro
Screenshot_20231019_211352_Authenticator Pro

### Award Wallet
This is a dark mode icon for **Award Wallet**. The grey icon is visible enough on dark backgrounds, but they use a white icon for dark backgrounds as it still keeps a small light-grey part to remain recognizable.
awardwallet awardwallet_dark
Screenshot_20231019_211227_Authenticator Pro
Screenshot_20231019_211323_Authenticator Pro

### Hide.me
This is a dark mode icon for **Hide.me**. Since the silhouette is in the blue triangle it works on dark mode already, but the silhouette itself blends in with the background right now.
hideme_dark
Screenshot_20231023_164318_Authenticator Pro
Screenshot_20231023_164355_Authenticator Pro

### Steam
I've read the discussion about **Steam** interchangeably using three icon, so I thought 'maybe a compromise?' How about using the default gradient icon for light mode and the white icon for dark mode? Examples below
Screenshot_20231024_143312_Authenticator Pro
Screenshot_20231024_143348_Authenticator Pro
Screenshot_20231024_143513_Authenticator Pro

I didn't add these icons because this is against the guidelines and a bit excessive, but it can be good from a design standpoint, so can be added if necessary.

### Nintendo
I've seen the whole discussion about the Nintendo icon and I would like to offer 2 options.

_**Option 1. Red N**_
A simple solution, but I've seen it being used in different icon packs
nintendo_new
Screenshot_20231021_213918_Authenticator Pro
Screenshot_20231021_213854_Authenticator Pro

_**Option 2. Framed Red N**_
A so-called "micrologo" taken from wiki. Also a simple icon that still keeps Nintendo's identity
nintendo_new2
Screenshot_20231021_213748_Authenticator Pro
Screenshot_20231021_213820_Authenticator Pro

### IONOS
I really don't like the use of the text logo here, but if I change the icon to a favicon with transparent background it looks like a line (see below). I still can do it though. Like I said, I really don't like the use of the text logo.
ionos_new ionos_dark
Screenshot_20231022_154645_Authenticator Pro
Screenshot_20231022_154742_Authenticator Pro

### Obsidian.md
It's been just recently added in #932 by @ch3thanhs and is based on the branding guidelines, but it's an app icon and a flatter icon is used on the main page, as a favicon and as a part of the logo. So I propose to use this flatter icon instead of the app icon.
obsidianmd_dark
Screenshot_20231023_232232_Authenticator Pro
Screenshot_20231023_232159_Authenticator Pro

### NameSilo
It definitely needs a dark mode icon, I just couldn't find any guidelines so I don't know which option to choose.
**a)** If the the background/frame is important, we just reverse colors and leave it at that.
Screenshot_20231025_013819_Authenticator Pro
Screenshot_20231025_013732_Authenticator Pro

**b)** If the background/frame is not important, we just remove it completely and leave the icon.
Screenshot_20231025_013902_Authenticator Pro
Screenshot_20231025_013957_Authenticator Pro

**c)** Or maybe even use a secondary color for the dark mode. After researching their website and blog it seems to be the most correct option.
Screenshot_20231025_211750_Authenticator Pro

### EVE Online
They have a favicon and I'm trying to remove text logos, but I don't know if this is too much. Looks good on the tile display option though.

### CODE REVIEW

**Comment by OmarNazzal150** [comment]
Hi Kvasenok. I'm trying to create a pull request. But it gives me this error

**Comment by Kvasenok** [comment]
Hi @OmarNazzal150 
I really don't know, seems to be some kinda bug, maybe try again later. What icons did you want to add?

**Comment by OmarNazzal150** [comment]
Here are the list 

1: https://www.spri.ng/ 

2 https://test.de/ 

3: https://studioninja.co/

4: https://talkdesk.com/

5: https://teslafi.com/

6: https://www.thrivecart.com/

7: https://timetastic.co.uk/

8: https://ti.to/

9: https://trimble.com/

10: https://www.turbosquid.com/

11: https://www.unleashedsoftware.com/

12: https://usabilla.com/

13: https://vagaro.com/

14: https://vivaldi.com/

15: https://vivup.co.uk/

16: https://weclapp.com/

17: https://wellfound.com/

18: https://whimsical.com/

19: https://workato.com/

20: https://xplenty.com/

21: https://yclas.com/

**Comment by Kvasenok** [comment]
@OmarNazzal150 oh my... Have you checked them all against Similarweb's ranking and the all itself? For example, spri.ng is already included

**Comment by OmarNazzal150** [comment]
I can't. It is because when i open Similar web, it forces me to create an account. To view a web It needs an account. So . I will not put my real email or use a temporary mail instead. Or check it by yourself.

**Comment by OmarNazzal150** [comment]
Here's a screen recording https://github.com/jamie-mh/AuthenticatorPro/assets/135146653/f5e6abc0-9582-4e89-9539-902e903bd695

**Comment by Kvasenok** [comment]
@OmarNazzal150 I'm sorry, but I don't know what you're talking about. [Similarweb](https://www.similarweb.com/) doesn't require to log in to search a website and check it for it's ranking

**Comment by OmarNazzal150** [comment]
Now, what should I do?. I'm sorry I can't check the ranking global. Just check it by yourself

**Comment by Kvasenok** [comment]
@OmarNazzal150 please create a separate icon request as usual

**Comment by OmarNazzal150** [comment]
First icon. https://cloudconvert.com/

**Comment by Kvasenok** [comment]
@OmarNazzal150 I mean please create an issue with icon request according to instructions

**Comment by OmarNazzal150** [comment]
Okay 👌🏻

**Comment by OmarNazzal150** [comment]
At 1001#

**Comment by Kvasenok** [comment]
@OmarNazzal150 
1. spri.ng already has a dark theme icon
2. There is already a Gosuslugi icon in the app
3. Please, stop using my PRs as an icon requst thread. You should create an issue with your requests according to instructions. Thank you.

**Comment by OmarNazzal150** [comment]
Ok

**Comment by Kvasenok** [comment]
I think I'm done.
@jamie-mh, all I can do is add the icons I mentioned in my P.S., otherwise ready to merge.

**Comment by Kvasenok** [comment]
I don't know why it suddenly started to give me a check error.
And yes, I keep finding something to update, but this PR can be merged any time, I'll just create a new one.

**Comment by Kvasenok** [comment]
@jamie-mh 
I'm totally done. See the first comment for the up to date info.

**Comment by jamie-mh** [comment]
Hi @Kvasenok ,

Thanks, very nice work once again. There's not much to add, but here are just a couple comments:

- I think the old Borgbase icon is more "correct". They only have black and white icons.
- The Uber icon "U" isn't used by Uber themselves. They use the full logotype, so we should probably stick to that.

As for your suggestions, I think you're correct about the Bitrix24, Wise, Award Wallet, Hide Me and Steam icons. They lack contrast in the dark mode currently, and your improvements are good.

- The Nintendo micrologo is pretty neat, I think we should use that.
- The Ionos "I" icon is better than the text logo. We can remove the 1&1 logo as it's obsolete now.
- The flat Obsidian icon is more correct, I agree.
- The secondary colour NameSilo icon is good. I think we should keep the frame, as that's part of their logo.
- I'm not too sure about the Eve Online icon, best leave it as-is for now.

Thanks

**Comment by Kvasenok** [comment]
@jamie-mh 
Thanks for the comments!
I've updated the icons accordingly.
Reverted changes for Borgbase and Uber, added dark mode icons for Bitrix24, Wise, Award Wallet, Hide Me, NameSilo and Steam and updated icons for Nintendo and IONOS. I've also deleted the 1&1 icon .

**Comment by Kvasenok** [comment]
I've tried to find a better dark mode icon for CodeShip couldn't understand something. Does it need its own icon at all? I have no idea what kind of service this is and all I could find out with quick googling is that it's part of CloudBees and probably(?) uses the same account. Shouldn't we have the CloudBees icon instead of CodeShip?

**Comment by jamie-mh** [comment]
It looks like a standalone product with its own accounts, so it makes sense to have a CodeShip icon in this case.

**Comment by Kvasenok** [comment]
> It looks like a standalone product with its own accounts, so it makes sense to have a CodeShip icon in this case.

Ok. I still want to find a better dark mode icon for it because the current one makes the two icon look like they have different size, since one has a white circle.

**Comment by jamie-mh** [comment]
Yes, that looks good. It's much better if the light and dark versions are the same size.

**Comment by Kvasenok** [comment]
> Yes, that looks good. It's much better if the light and dark versions are the same size.

Done. If you have any thoughts about alternative icons for Call of Duty and Control D, I can still update them. Otherwise I don't have anything to add and this PR is ready for merge.

**Comment by jamie-mh** [comment]
It all looks good to me. Thanks again!

**Pull request merged**
