### PR TITLE
Added logos

### PR DESCRIPTION
**Pull request by l-marchesi**
Added the following logos:
- Arduino: maybe without the wording "Arduino"?
- Balena
- Google Pay
- ServerTown: Is a small swiss hosting provider, not that known. Best logo I could find

### CODE REVIEW

**Comment by jamie-mh** [comment]
Hi @l-marchesi ,

Thanks for your PR, but it seems you forget to include the icon images :)

**Comment by l-marchesi** [comment]
Hi @jamie-mh 
Whoops. How embarrassing 🙈
Now I've added them :)

**Comment by jamie-mh** [comment]
Thanks.
Can you remove the text from the Arduino logo? I think it would look better without it.

**Comment by l-marchesi** [comment]
You're welcome - I removed the text from the logo.
The script "generate_icons.py" didn't want to regenerate the logos, so I manually deleted and regenerated them.

**Comment by jamie-mh** [comment]
Very nice, thanks.
FYI: The script skips already generated icons so that optimised icons aren't overwritten, that's why they must be deleted in order to regenerate them.

**Pull request merged**
