### PR TITLE
Add icons for T-Mobile, NiceHash, Plex, and Best Buy

### PR DESCRIPTION
**Pull request by trimeta**
Like the title says, adding two more icons (well, three, since NiceHash has a separate dark theme icon). All icons taken directly from their respective websites (in the case of T-Mobile's, further cropped to maximize space) and resized.

### CODE REVIEW

**Comment by trimeta** [comment]
Note that I'm using the full Plex wordmark, instead of the smaller icon, because according to their [brand guildlines](https://brand.plex.tv/d/qxmJ3odkK0fj/style-guide) the smaller logo is just the app icon and should only be used for the app. Also, yes, I used the "flat" style, and gave the dark-mode version a transparent background.

**Comment by trimeta** [comment]
Added some Best Buy logos. Unfortunately, their [press page](https://corporate.bestbuy.com/media-faq/) says they only release logos upon request, which didn't seem likely to work. [This article](https://www.theverge.com/2018/5/9/17334848/best-buy-logo-design-san-serif-font-shopping-tag) had a pretty comprehensive look at the different formats, however. Because Best Buy's image is so tied into white-on-blue, I left that as an option, in addition to transparent-background versions: feel free to delete and/or rename until this matches the Authenticator Pro style.

**Comment by jamie-mh** [comment]
Hi @trimeta ,

Thanks for contributing these icons.

A few tweaks:
- The Best Buy icon is too large, it should be 128x128. Also reduce the transparent space on the edges as much as possible. Not fond of the blue icon, it doesn't match the style of the others which don't have a solid background.
- The NiceHash logo is outdated: [here is the latest version](https://www.nicehash.com/media). I don't think the new one needs a dark variant.
- The Plex guidelines state that the full logomark should be used when referring to the company. Since we're referring to the application, it is perfectly reasonable to use the app icon or simply the "X" from the full logo. It would look better.

Thanks

**Comment by trimeta** [comment]
Huh, NiceHash updated their logo [yesterday](https://www.nicehash.com/blog/post/nicehash-gets-a-new-look), the brand page must have still been using the old version when I downloaded those logos. I fixed those (you're right, the new edition doesn't have a distinct dark-mode logo), as well as resizing and trimming the light-mode Best Buy logo (an oversight on my part) and removing the white-on-blue Best Buy logo. For the Plex logo, I put in two versions, one with the original black background (for light mode, to retain the yellow-on-black), and one with the background made transparent (for dark mode, where you've already got black). I suspect having the yellow directly on white would look weird, but making the dark-mode logo (with its transparent background) the only logo is also an option, I suppose.

**Comment by jamie-mh** [comment]
Thanks

**Pull request merged**
