### PR TITLE
Update Wear OS Screenshots and add new icons

### PR DESCRIPTION
**Pull request by ch3thanhs**
Added a transparent background to the Wear OS screenshots

### CODE REVIEW

**Comment by ch3thanhs** [comment]
I have also added icons for openai.com and substack.com, both are ranked within top 200,000 on Similarweb.

**Comment by jamie-mh** [comment]
Hi @ch3thanhs ,

Thanks for contributing.
Can you please run the screenshots through an optimiser such as TinyPng, they're much larger than the originals. The icons are good.

Thanks!

**Comment by ch3thanhs** [comment]
Hi @jamie-mh,

I have made the necessary changes to the screenshots.

**Comment by jamie-mh** [comment]
Thanks!

**Pull request merged**
